from django.urls import path
from smscampaigns_app.views.sms_campaigns_views import (saveSendSmsCampaign, getSmsCampaignList, deleteSmsCampaign, getSmsCampaignById, finalSendSmsCampaign, getSmsCampaignReportById, getSmsCampaignReportDashboard, getBuyAllSmsNumberList, checkSmsCampaignNameExists, getSmsCampaignTransactionList, getSmsCampaignDetailsById, getBuyAllSmsConversationsNumberList, getMemberSmsSetting, getMemberSmsConversationsSetting, closeAllSmsConversations, finalizeSmsCampaignQuestionOrder, getMemberCallForwardingNumber, saveMemberCallForwardingNumber, getSmsTemplateList, saveSmsTemplate, deleteSmsTemplate, getSmsTemplateById, getSmsCampaignPreview, editSmsCampaignSchedule, saveSmsCampaign, sendSmsCampaign, sendSmsPreview, buyNumberForSmsCampaign, getSmsCampaignPhoneList, getSmsCampaignReleasePhoneList, deleteSmsCampaignNumber, changeSmsCampaignNumber, smsStatusUrl, smsStatusReplyUrl, closeSmsCampaign, getNumberCheck, getScmNumberPhoneSid, getFreeNumberList, getSmsCampaignNumber, smsLinkClick, getSmsCampaignReplyNotification, setCampaignNumber, checkNumberAssignOrNot, getUsernamePassword)
from smscampaigns_app.views.sms_campaigns_report_views import (get_sms_campaigns_report_list_page, get_sms_campaigns_report_dashboard, get_sms_campaigns_sms_reports_deliveries_data, get_sms_campaigns_mms_reports_deliveries_data, get_sms_campaigns_reports_undelivered_data, get_sms_campaigns_reports_not_sent_data, get_sms_campaigns_report_replies_data, get_sms_campaigns_reports_unsubscribed_data, get_sms_campaigns_reports_links_data, get_sms_campaigns_reports_links_data_details, get_sms_campaigns_report_data_for_pdf)

urlpatterns = [
    path('smsCampaign/saveSendSmsCampaign', saveSendSmsCampaign),
    path('smsCampaign/getSmsCampaignList', getSmsCampaignList),
    path('smsCampaign/deleteSmsCampaign', deleteSmsCampaign),
    path('smsCampaign/getSmsCampaign', getSmsCampaignById), # getSmsCampaign in Java
    path('smsCampaign/finalSendSmsCampaign', finalSendSmsCampaign),
    path('smsCampaign/getSmsCampaignReportById/<int:smsId>', getSmsCampaignReportById),
    path('smsCampaign/getSmsCampaignReportDashboard/<int:smsId>', getSmsCampaignReportDashboard),
    path('smsCampaign/getBuyAllSmsNumberList', getBuyAllSmsNumberList),
    path('smsCampaign/checkSmsCampaignNameExists', checkSmsCampaignNameExists),
    path('smsCampaign/getSmsCampaignTransactionList', getSmsCampaignTransactionList),
    path('smsCampaign/getSmsCampaignDetailsById/<int:smsId>', getSmsCampaignDetailsById),
    path('smsCampaign/getBuyAllSmsConversationsNumberList', getBuyAllSmsConversationsNumberList),
    path('smsCampaign/getMemberSmsSetting', getMemberSmsSetting),
    path('smsCampaign/getMemberSmsConversationsSetting', getMemberSmsConversationsSetting),
    path('smsCampaign/closeAllSmsConversations', closeAllSmsConversations),
    path('smsCampaign/finalizeSmsCampaignQuestionOrder', finalizeSmsCampaignQuestionOrder),
    path('smsCampaign/getMemberCallForwardingNumber', getMemberCallForwardingNumber),
    path('smsCampaign/saveMemberCallForwardingNumber', saveMemberCallForwardingNumber),
    path('smsCampaign/getSmsTemplateList', getSmsTemplateList),
    path('smsCampaign/saveSmsTemplate', saveSmsTemplate),
    path('smsCampaign/deleteSmsTemplate', deleteSmsTemplate),
    path('smsCampaign/getSmsTemplateById/<int:sstId>', getSmsTemplateById),
    path('smsCampaign/getSmsCampaignPreview', getSmsCampaignPreview),
    path('smsCampaign/editSmsCampaignSchedule', editSmsCampaignSchedule),
    path('smsCampaign/saveSmsCampaign', saveSmsCampaign),
    path('smsCampaign/sendSmsCampaign', sendSmsCampaign),
    path('smsCampaign/sendSmsPreview', sendSmsPreview),
    path('smsCampaign/buyNumberForSmsCampaign', buyNumberForSmsCampaign),
    path('smsCampaign/getSmsCampaignPhoneList/<int:subTenantId>', getSmsCampaignPhoneList),
    path('smsCampaign/getSmsCampaignReleasePhoneList/<int:subMemberId>', getSmsCampaignReleasePhoneList),
    path('smsCampaign/deleteSmsCampaignNumber/<int:tenant_id>/<int:sms_id>', deleteSmsCampaignNumber),
    path('smsCampaign/changeSmsCampaignNumber', changeSmsCampaignNumber),
    path('smsCampaign/smsStatusUrl', smsStatusUrl),
    path('smsCampaign/smsStatusReplyUrl', smsStatusReplyUrl),
    path('smsCampaign/closeSmsCampaign', closeSmsCampaign),
    path('smsCampaign/getNumberCheck/<int:groupId>', getNumberCheck),
    path('smsCampaign/getScmNumberPhoneSid', getScmNumberPhoneSid),
    path('smsCampaign/getFreeNumberList/', getFreeNumberList),
    path('smsCampaign/getSmsCampaignNumber/<int:smsId>', getSmsCampaignNumber),
    path('smsCampaign/smsLinkClick', smsLinkClick),
    path('smsCampaign/getSmsCampaignReplyNotification/<int:replyId>', getSmsCampaignReplyNotification),
    path('smsCampaign/setCampaignNumber', setCampaignNumber),
    path('smsCampaign/checkNumberAssignOrNot', checkNumberAssignOrNot),
    path('smsCampaign/getUsernamePassword', getUsernamePassword),

    # SmsCampaignsReportController endpoints
    path('smsCampaignReport/getSmsCampaignsReportListPage', get_sms_campaigns_report_list_page),
    path('smsCampaignReport/getSmsCampaignsReportDashboard', get_sms_campaigns_report_dashboard),
    path('smsCampaignReport/getSmsCampaignsSmsReportsDeliveriesData', get_sms_campaigns_sms_reports_deliveries_data),
    path('smsCampaignReport/getSmsCampaignsMmsReportsDeliveriesData', get_sms_campaigns_mms_reports_deliveries_data),
    path('smsCampaignReport/getSmsCampaignsReportsUndeliveredData', get_sms_campaigns_reports_undelivered_data),
    path('smsCampaignReport/getSmsCampaignsReportsNotSentData', get_sms_campaigns_reports_not_sent_data),
    path('smsCampaignReport/getSmsCampaignsReportRepliesData', get_sms_campaigns_report_replies_data),
    path('smsCampaignReport/getSmsCampaignsReportsUnsubscribedData', get_sms_campaigns_reports_unsubscribed_data),
    path('smsCampaignReport/getSmsCampaignsReportsLinksData', get_sms_campaigns_reports_links_data),
    path('smsCampaignReport/getSmsCampaignsReportsLinksDataDetails', get_sms_campaigns_reports_links_data_details),
    path('smsCampaignReport/getSmsCampaignsReportDataForPdf', get_sms_campaigns_report_data_for_pdf),
]
