from rest_framework.views import exception_handler
from rest_framework.exceptions import NotAuthenticated, AuthenticationFailed, PermissionDenied

def jwt_403_exception_handler(exc, context):
    """
    Catch API Exceptions generated by Token Authentication and 
    force formatting them identically to Java's `JwtRequestFilter.java` 403 Response.
    """
    response = exception_handler(exc, context)
    
    if isinstance(exc, (NotAuthenticated, AuthenticationFailed, PermissionDenied)):
        custom_data = {
            "msg": "Access Denied",
            "code": 403,
            "status": "failure"
        }
        if response is not None:
            response.data = custom_data
            response.status_code = 403
            
    return response
