from rest_framework import serializers

class EditCampaignScheduleSerializer(serializers.Serializer):
    campId = serializers.IntegerField()
    sendOnDate = serializers.CharField()
    scheduleId = serializers.IntegerField(required=False)
    timeZone = serializers.CharField(required=False, allow_blank=True)
    throttling = serializers.CharField(required=False, allow_blank=True)
    throttlingType = serializers.CharField(required=False, allow_null=True, allow_blank=True)

class DeleteCampaignSerializer(serializers.Serializer):
    campId = serializers.ListField(child=serializers.IntegerField())

class ResendAllCampaignSerializer(serializers.Serializer):
    memberId = serializers.IntegerField()
    sendOnDate = serializers.CharField()
    campId = serializers.IntegerField()
    campSendId = serializers.IntegerField()
    totalMember = serializers.IntegerField()

class SendCampaignSerializer(serializers.Serializer):
    memberId = serializers.IntegerField(required=False)
    campType = serializers.IntegerField(required=False)
    campName = serializers.CharField()
    mailType = serializers.CharField(required=False, allow_blank=True)
    campDesc = serializers.CharField(required=False, allow_blank=True)
    fromName = serializers.CharField()
    subject = serializers.CharField()
    fromAdd = serializers.CharField()
    replyToAdd = serializers.CharField()
    schType = serializers.IntegerField(required=False)
    sendOnDateTime = serializers.CharField(required=False, allow_blank=True)
    selectedGid = serializers.IntegerField(required=False)
    selectedSid = serializers.IntegerField(required=False)
    selectedAllSid = serializers.ListField(child=serializers.IntegerField(), required=False)
    allTempData = serializers.CharField(required=False, allow_blank=True)
    myPageId = serializers.IntegerField(required=False)
    campMainType = serializers.IntegerField(required=False)
    subjectB = serializers.CharField(required=False, allow_blank=True)
    schTypeB = serializers.IntegerField(required=False)
    sendOnDateTimeB = serializers.CharField(required=False, allow_blank=True)
    myPageIdB = serializers.IntegerField(required=False)
    fromNameB = serializers.CharField(required=False, allow_blank=True)
    allTempDataB = serializers.CharField(required=False, allow_blank=True)
    testingType = serializers.IntegerField(required=False)
    selectGroupPer = serializers.IntegerField(required=False)
    remainGroupPer = serializers.IntegerField(required=False)
    byAutoManual = serializers.CharField(required=False, allow_blank=True)
    byType = serializers.CharField(required=False, allow_blank=True)
    byNumber = serializers.IntegerField(required=False)
    byMeasure = serializers.CharField(required=False, allow_blank=True)
    incrementalUpdates = serializers.CharField(required=False, allow_blank=True)
    checkSpamYN = serializers.CharField(required=False, allow_blank=True)
    timeZone = serializers.CharField(required=False, allow_blank=True)
    contactSelected = serializers.ListField(child=serializers.CharField(), required=False)
    mpType = serializers.IntegerField(required=False)
    mpTypeB = serializers.IntegerField(required=False)
    throttling = serializers.CharField(required=False, allow_blank=True)
    throttlingType = serializers.CharField(required=False, allow_blank=True)
    throttlingValue = serializers.IntegerField(required=False)

class SaveSendCampaignSerializer(serializers.Serializer):
    memberId = serializers.IntegerField()
    cid = serializers.IntegerField(required=False)
    campId = serializers.IntegerField()
    memberList = serializers.IntegerField()
    msg = serializers.CharField(required=False, allow_blank=True)

class CheckSpamSerializer(serializers.Serializer):
    domainName = serializers.CharField(required=False, allow_blank=True)
    domainVerify = serializers.BooleanField(required=False)
    dkim = serializers.IntegerField(required=False)
    spf = serializers.IntegerField(required=False)
    campName = serializers.CharField(required=False, allow_blank=True)
    allTempData = serializers.CharField(required=False, allow_blank=True)
    myPageId = serializers.IntegerField(required=False)
    selectedGid = serializers.IntegerField(required=False)
    replyToAdd = serializers.CharField(required=False, allow_blank=True)
    fromName = serializers.CharField(required=False, allow_blank=True)
    subject = serializers.CharField(required=False, allow_blank=True)
    fromAdd = serializers.CharField(required=False, allow_blank=True)
    testingType = serializers.IntegerField(required=False)
    subjectB = serializers.CharField(required=False, allow_blank=True)
    allTempDataB = serializers.CharField(required=False, allow_blank=True)
    myPageIdB = serializers.IntegerField(required=False)
    fromNameB = serializers.CharField(required=False, allow_blank=True)
    checkSpamYN = serializers.CharField(required=False, allow_blank=True)

class ThrottlingValidationSerializer(serializers.Serializer):
    selectedGid = serializers.IntegerField(required=False)
    selectedSid = serializers.IntegerField(required=False)
    selectedAllSid = serializers.ListField(child=serializers.IntegerField(), required=False)
    fromAdd = serializers.CharField()
    throttlingType = serializers.CharField()
    throttlingValue = serializers.IntegerField()
    sendOnDateTime = serializers.CharField()
    schType = serializers.IntegerField()